//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cascading_Style_Sheets
    {
        public Cascading_Style_Sheets()
        {
            this.Layout = new HashSet<Layout>();
            this.Page_Content = new HashSet<Page_Content>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<Layout> Layout { get; set; }
        public virtual ICollection<Page_Content> Page_Content { get; set; }
    }
}
