//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component_Bind
    {
        public int Id { get; set; }
        public int Columnd_Id { get; set; }
        public int Component_Id { get; set; }
        public string Component_Type { get; set; }
    
        public virtual Column Column { get; set; }
        public virtual Component Component { get; set; }
    }
}
