//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public Component()
        {
            this.Component_Bind = new HashSet<Component_Bind>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Component_Type_Id { get; set; }
        public string HTML_content { get; set; }
    
        public virtual ICollection<Component_Bind> Component_Bind { get; set; }
        public virtual Component_Type Component_Type { get; set; }
    }
}
