//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Header
    {
        public Page_Header()
        {
            this.Page_Content = new HashSet<Page_Content>();
        }
    
        public int Id { get; set; }
        public string HTML_content { get; set; }
    
        public virtual ICollection<Page_Content> Page_Content { get; set; }
    }
}
