//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Content
    {
        public Page_Content()
        {
            this.View = new HashSet<View>();
            this.Cascading_Style_Sheets = new HashSet<Cascading_Style_Sheets>();
            this.JavaScript_Files = new HashSet<JavaScript_Files>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Container_Id { get; set; }
        public Nullable<int> Main_Content_Id { get; set; }
        public Nullable<int> Page_Header_Id { get; set; }
        public Nullable<int> Page_Sidebar_Id { get; set; }
        public string HTML_content { get; set; }
    
        public virtual Layout_Container Layout_Container { get; set; }
        public virtual Page_Main_Content Page_Main_Content { get; set; }
        public virtual Page_Header Page_Header { get; set; }
        public virtual Page_Sidebar Page_Sidebar { get; set; }
        public virtual ICollection<View> View { get; set; }
        public virtual ICollection<Cascading_Style_Sheets> Cascading_Style_Sheets { get; set; }
        public virtual ICollection<JavaScript_Files> JavaScript_Files { get; set; }
    }
}
