//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Main_Content
    {
        public Page_Main_Content()
        {
            this.Page_Content = new HashSet<Page_Content>();
            this.Row_Binding = new HashSet<Row_Binding>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Page_Content_Id { get; set; }
        public string HTML_content { get; set; }
    
        public virtual ICollection<Page_Content> Page_Content { get; set; }
        public virtual ICollection<Row_Binding> Row_Binding { get; set; }
    }
}
