//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row
    {
        public Row()
        {
            this.Column_Binding = new HashSet<Column_Binding>();
            this.Row_Binding = new HashSet<Row_Binding>();
        }
    
        public int Id { get; set; }
        public string Class { get; set; }
        public string HTML_content { get; set; }
    
        public virtual ICollection<Column_Binding> Column_Binding { get; set; }
        public virtual ICollection<Row_Binding> Row_Binding { get; set; }
    }
}
