//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Row_Binding
    {
        public int Main_Content_Id { get; set; }
        public int Row_Id { get; set; }
        public int Order { get; set; }
    
        public virtual Page_Main_Content Page_Main_Content { get; set; }
        public virtual Row Row { get; set; }
    }
}
