//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAV_database : DbContext
    {
        public SAV_database()
            : base("name=SAV_database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cascading_Style_Sheets> Cascading_Style_Sheets { get; set; }
        public DbSet<Column> Column { get; set; }
        public DbSet<Column_Binding> Column_Binding { get; set; }
        public DbSet<Component> Component { get; set; }
        public DbSet<Component_Bind> Component_Bind { get; set; }
        public DbSet<Component_Type> Component_Type { get; set; }
        public DbSet<JavaScript_Files> JavaScript_Files { get; set; }
        public DbSet<Layout> Layout { get; set; }
        public DbSet<Layout_Container> Layout_Container { get; set; }
        public DbSet<Layout_Header> Layout_Header { get; set; }
        public DbSet<Page_Content> Page_Content { get; set; }
        public DbSet<Page_Header> Page_Header { get; set; }
        public DbSet<Page_Main_Content> Page_Main_Content { get; set; }
        public DbSet<Page_Sidebar> Page_Sidebar { get; set; }
        public DbSet<Row> Row { get; set; }
        public DbSet<View> View { get; set; }
        public DbSet<Row_Binding> Row_Binding { get; set; }
    }
}
