//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAV.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Layout_Id { get; set; }
        public Nullable<int> Page_Content_Id { get; set; }
    
        public virtual Layout Layout { get; set; }
        public virtual Page_Content Page_Content { get; set; }
    }
}
